<a href="https://colab.research.google.com/github/MADHKOUR-Khalil/Angular10dotNETCoreAPI/blob/master/Trafic_%3E_AGG_%3EValid%C3%A9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Env Spark

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
pip install pyspark

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting pyspark
  Downloading pyspark-3.2.1.tar.gz (281.4 MB)
     |████████████████████████████████| 281.4 MB 35 kB/s
Collecting py4j==0.10.9.3
  Downloading py4j-0.10.9.3-py2.py3-none-any.whl (198 kB)
     |████████████████████████████████| 198 kB 48.6 MB/s
Building wheels for collected packages: pyspark
  Building wheel for pyspark (setup.py) ... done
  Created wheel for pyspark: filename=pyspark-3.2.1-py2.py3-none-any.whl size=281853642 sha256=648fa7dabe359513c196d94071cf38662327f3703e2a05cf22e9d9cd18b7e7e5
  Stored in directory: /root/.cache/pip/wheels/9f/f5/07/7cd8017084dce4e93e84e92efd1e1d5334db05f2e83bcef74f
Successfully built pyspark
Installing collected packages: py4j, pyspark
Successfully installed py4j-0.10.9.3 pyspark-3.2.1

In [ ]:
from pyspark.context import SparkContext
sc = SparkContext()
from pyspark.sql.session import SparkSession
spark = SparkSession(sc)
from pyspark.sql import SQLContext
sqlContext = SQLContext(sc)

/usr/local/lib/python3.7/dist-packages/pyspark/sql/context.py:79: FutureWarning: Deprecated in 3.0.0. Use SparkSession.builder.getOrCreate() instead.
  FutureWarning

In [ ]:
import pyspark
from pyspark.sql.functions import count as _count
from pyspark.sql.functions import sum as _sum
import pyspark.sql.functions as psf
import pandas as pd

#Flux Done(MSC, CCN, MMG, MMS)

#Importation des fichier trafic

In [ ]:
#create dataframe from csv  file
CCNdf =sqlContext.read.csv(header="true", path = "/content/drive/MyDrive/20220501/CCN/*.csv")

In [ ]:
CCNdf.write.option("header",True).csv("/content/drive/MyDrive/all.csv")

In [ ]:
#create dataframe from csv  file
MSCdf =sqlContext.read.csv(header="true", path = "/content/drive/MyDrive/20220413/MSC/*.csv")
CCNdf_msc =sqlContext.read.csv(header="true", path = "/content/drive/MyDrive/20220413/CCN/*.csv")

CCNdf =sqlContext.read.csv(header="true", path = "/content/drive/MyDrive/20220501/CCN/*.csv")

#CCNdf_mms =sqlContext.read.csv(header="true", path = "/content/drive/MyDrive/20220501/CCN/*.csv")

MMSdf =sqlContext.read.csv(header="true", path = "/content/drive/MyDrive/20220501/MMS/*.csv")

PSMdf =sqlContext.read.csv(header="true", path = "/content/drive/MyDrive/20220501/PSM/*.csv")

MMGdf =sqlContext.read.csv(header="true", path = "/content/drive/MyDrive/20220501/MMG/*.csv")

In [ ]:
CCNdf.count()

776613

In [ ]:
a=4531391
b=1500311
print('MSC nbr linge le 13/04/2022 ')
print(MSCdf.count())
print('CCN nbr linge le 13/04/2022 ')
print(CCNdf.count())

MSC nbr linge le 13/04/2022
4531391
CCN nbr linge le 13/04/2022
776613

In [ ]:
print("MSC")
MSCdf.show(5)

print("CCN")
CCNdf.show(5)

print("MMG")
MMGdf.show(5)

print("MMS")
MMSdf.show(5)

print("PSM")
PSMdf.show(5)

MSC
+--------------------+---+---------------+-----------+-------------+--------------+--------------------+------+-----------+-------------+--------------+---------+-----------------+--------------------+--------------+-------------+----------------+------------------+-----+-------------+-----------+----------------+--------------+-------------+----------------+--------------+------------+----------+---------------+--------------------+-----------+----+------------+----+---------------+--------------+-------+------------+--------------------+--------------------+--------------+---------+----------+---------+---------+-------------+--------------------+------------+-------------+----------+---------------+--------------------+------------+----------+--------------------+----------+---------------+-----------+---------+-----+-----+-----+------------+--------+---------+
|   AGGREGATION_GROUP|APN|         A_IMSI|   A_MSISDN|A_MSISDN_ORIG|BEARER_SERVICE|        B_DATASOURCE|B_IMSI|   B_MSISDN|B_MSISDN_ORIG|CALL_REFERENCE|CALL_TYPE|CAUSE_FOR_CLOSING|CDR_SEARCH_DETAIL_ID|       CELL_ID|   CGI_ID_KEY|CHARGE_AMNT_STEP|CHARGE_AMOUNT_ORIG|C_NUM|   C_NUM_ORIG|DATA_VOLUME|DATA_VOLUME_DOWN|DATA_VOLUME_UP|DURATION_STEP|ESTIMATED_AMOUNT|EVENT_DURATION|EVENT_STATUS|EVENT_TYPE|EVENT_TYPE_ORIG|            FILENAME|FILTER_CODE|IMEI|LAST_PARTIAL|  NE|ORIG_START_TIME|PARTIAL_SEQ_ID|PARTNER|PARTNER_CODE|         PGW_ADDRESS|     PRICE_PLAN_CODE|     PROC_DATE|PROC_HOUR|RADIO_TYPE|RATE_CODE|RECORD_ID|RECORD_STATUS|         RECORD_TYPE|ROAMING_TYPE|  SERVED_MSRN|SERVICE_ID|SERVICE_PARTNER|        SERVICE_TYPE|SGSN_ADDRESS|SMS_CENTRE|START_DATE_TIME_HOME|START_TIME|SUBSCRIBER_TYPE|TELESERVICE|TEST_FLAG|TON_A|TON_B|TON_C|TRAFFIC_TYPE|TRUNK_IN|TRUNK_OUT|
+--------------------+---+---------------+-----------+-------------+--------------+--------------------+------+-----------+-------------+--------------+---------+-----------------+--------------------+--------------+-------------+----------------+------------------+-----+-------------+-----------+----------------+--------------+-------------+----------------+--------------+------------+----------+---------------+--------------------+-----------+----+------------+----+---------------+--------------+-------+------------+--------------------+--------------------+--------------+---------+----------+---------+---------+-------------+--------------------+------------+-------------+----------+---------------+--------------------+------------+----------+--------------------+----------+---------------+-----------+---------+-----+-----+-----+------------+--------+---------+
|TUNISIA-Mobile Tu...| _N|605020800720031|21696239139|1121696239139|            _N|TUNISIA-Mobile Tu...|    _N|21698390084|1121698390084|            _N|      SMS|               _N|         59940517091|06F5200082A104|           _N|              _N|                _N|   _N|1121696239139|         _N|              _N|            _N|        [0-1[|              _N|             0|          _N|         6|             _N|MS35.4387.2022041...|         _N|  _N|          _N|MS35|   220413103829|            _N|  TUNTT|          FF|TUNISIA-Mobile Tu...|TUNISIA-Mobile Tu...|20220413000000|       10|        _N|       _N|       _N|           _N|mSTerminatingSMSi...|          _N|           _N|        _N|             FF|mSTerminatingSMSi...|          _N|        _N|                  _N|         0|            HYB|         21|      _UN|  _UN|11216|  _UN|           1|      _N|       _N|
|TUNISIA-Mobile Tu...| _N|605020715357180|21697285265|1121697285265|            _N|TUNISIA-Mobile Tu...|    _N|21694171280|   1494171280|  145489264640|    VOICE|               00|         59940517092|06F520008233B0|1015208214528|              _N|                _N|   _N|1121697285265|         _N|              _N|            _N|       [1-30[|              _N|            27|        09C2|         2|             _N|MS35.4387.2022041...|         _N|  _N|          _N|MS35|   220413103803|            _N|  TUNTT|          _N|TUNISIA-Mobile Tu...|TUNISIA-Mobile Tu...|20220413000000|       10|        _N|       _N|       _N|           _N|       mSTerminating|          _N|1121698011263|        _N|             _N|      mSTerminating_|          _N|        _N|                  _N|         0|        PREPAID|         11|      _UN|  _UN|11216|  _UN|           1| SOUBC1I|  BSOEVOO|
|TUNISIA-Mobile Tu...| _N|605020820885950|21692715782|1121692715782|            _N|TUNISIA-Mobile Tu...|    _N|21698390084|1121698390084|            _N|      SMS|               _N|         59940517093|06F52008347D57|           _N|              _N|                _N|   _N|1121692715782|         _N|              _N|            _N|        [0-1[|              _N|             0|          _N|         6|             _N|MS35.4387.2022041...|         _N|  _N|          _N|MS35|   220413103829|            _N|  TUNTT|          FF|TUNISIA-Mobile Tu...|TUNISIA-Mobile Tu...|20220413000000|       10|        _N|       _N|       _N|           _N|mSTerminatingSMSi...|          _N|           _N|        _N|             FF|mSTerminatingSMSi...|          _N|        _N|                  _N|         0|        PREPAID|         21|      _UN|  _UN|11216|  _UN|           1|      _N|  NABRN1O|
|TUNISIA-Mobile Or...| _N|605020807900476|21696906404|1121696906404|            _N|TUNISIA-Mobile Tu...|    _N|21654127711|   1454127711|  142386790400|    VOICE|               00|         59940517094|06F520005A8023|1082200162304|              _N|                _N|   _N|1121696906404|         _N|              _N|            _N|   [600-7200[|              _N|           638|          _N|         2|             _N|MS35.4387.2022041...|         _N|  _N|          _N|MS35|   220413102752|            _N|  TUNOR|          _N|TUNISIA-Mobile Or...|TUNISIA-Mobile Tu...|20220413000000|       10|        _N|       _N|        Y|           _N|       mSTerminating|          _N|1121698012423|        _N|             _N|      mSTerminating_|          _N|        _N|                  _N|         0|        PREPAID|         11|      _UN|  _UN|11216|  _UN|           1| SOUBC1I|  BNABEVO|
|TUNISIA-Mobile Tu...| _N|605020816450864|21692730804|   1492730804|            _N|TUNISIA-Mobile Oo...|    _N|21625949580|1210825949580|  145438277632|    VOICE|               00|         59940517095|06F520019CC635|           _N|              _N|                _N|   _N|1210825949580|         _N|              _N|            _N|      [30-60[|              _N|            42|          _N|         1|             _N|MS35.4387.2022041...|         _N|  _N|          _N|MS35|   220413103747|            _N|  TUNTA|          _N|TUNISIA-Mobile Tu...|TUNISIA-Mobile Oo...|20220413000000|       10|        _N|       _N|        Y|           _N|       mSOriginating|          _N|           _N|        _N|             _N|      mSOriginating_|          _N|        _N|                  _N|         0|        PREPAID|         11|      _UN|  _UN|12108|  _UN|           1| BORDH1I|   SSFDJO|
+--------------------+---+---------------+-----------+-------------+--------------+--------------------+------+-----------+-------------+--------------+---------+-----------------+--------------------+--------------+-------------+----------------+------------------+-----+-------------+-----------+----------------+--------------+-------------+----------------+--------------+------------+----------+---------------+--------------------+-----------+----+------------+----+---------------+--------------+-------+------------+--------------------+--------------------+--------------+---------+----------+---------+---------+-------------+--------------------+------------+-------------+----------+---------------+--------------------+------------+----------+--------------------+----------+---------------+-----------+---------+-----+-----+-----+------------+--------+---------+
only showing top 5 rows

CCN
+-----------------+---+------+-----------+-------------+--------------+------------+------+-----------+-------------+--------------+---------+-----------------+--------------------+-------+----------+----------------+------------------+------+----------+-----------+----------------+--------------+-------------+----------------+--------------+------------+----------+---------------+--------------------+-----------+----+------------+-----------+---------------+--------------+-------+------------+-----------+---------------+--------------+---------+----------+---------+---------+-------------+-----------------+------------+-----------+----------+---------------+------------+------------+----------+--------------------+----------+---------------+-----------+---------+--------------------+--------------------+-----+------------+--------+---------+
|AGGREGATION_GROUP|APN|A_IMSI|   A_MSISDN|A_MSISDN_ORIG|BEARER_SERVICE|B_DATASOURCE|B_IMSI|   B_MSISDN|B_MSISDN_ORIG|CALL_REFERENCE|CALL_TYPE|CAUSE_FOR_CLOSING|CDR_SEARCH_DETAIL_ID|CELL_ID|CGI_ID_KEY|CHARGE_AMNT_STEP|CHARGE_AMOUNT_ORIG| C_NUM|C_NUM_ORIG|DATA_VOLUME|DATA_VOLUME_DOWN|DATA_VOLUME_UP|DURATION_STEP|ESTIMATED_AMOUNT|EVENT_DURATION|EVENT_STATUS|EVENT_TYPE|EVENT_TYPE_ORIG|            FILENAME|FILTER_CODE|IMEI|LAST_PARTIAL|         NE|ORIG_START_TIME|PARTIAL_SEQ_ID|PARTNER|PARTNER_CODE|PGW_ADDRESS|PRICE_PLAN_CODE|     PROC_DATE|PROC_HOUR|RADIO_TYPE|RATE_CODE|RECORD_ID|RECORD_STATUS|      RECORD_TYPE|ROAMING_TYPE|SERVED_MSRN|SERVICE_ID|SERVICE_PARTNER|SERVICE_TYPE|SGSN_ADDRESS|SMS_CENTRE|START_DATE_TIME_HOME|START_TIME|SUBSCRIBER_TYPE|TELESERVICE|TEST_FLAG|               TON_A|               TON_B|TON_C|TRAFFIC_TYPE|TRUNK_IN|TRUNK_OUT|
+-----------------+---+------+-----------+-------------+--------------+------------+------+-----------+-------------+--------------+---------+-----------------+--------------------+-------+----------+----------------+------------------+------+----------+-----------+----------------+--------------+-------------+----------------+--------------+------------+----------+---------------+--------------------+-----------+----+------------+-----------+---------------+--------------+-------+------------+-----------+---------------+--------------+---------+----------+---------+---------+-------------+-----------------+------------+-----------+----------+---------------+------------+------------+----------+--------------------+----------+---------------+-----------+---------+--------------------+--------------------+-----+------------+--------+---------+
|               _N| _N|    _N|21695547469|  21695547469|            _N|          _N|    _N|21622136759|   1A22136759|0_752328310784|    VOICE|               _N|         60055778211|     _N|        _N|              _N|             0.035|   0.0|       0.0|          0|              _N|            _N|           _N|              _N|             6|          _N|         1|             _N|CCN6_CDRCCN_4004_...|         _N|  _N|          _N|CDRCCN_4004| 20220501124120|            _N|  TUNTT|          _N|         _N|        TUNISIA|20220501000000|       11|        _N|      0.0|      0.0|         _N_0|mobileOriginating|        HOME|         _N|      1095|             _N|         _UN|          _N|     _N__N|      20220501000000|        12|        PREPAID|          0|      _UN|TUNISIA-Mobile Tu...|TUNISIA-Mobile Oo...|   _N|           1|    1.06|    1.095|
|               _N| _N|    _N|21698968358|  21698968358|            _N|          _N|    _N|21698934540|   1A98934540|0_955508326400|    VOICE|               _N|         60055778212|     _N|        _N|              _N|              0.05|473.95|     474.0|          0|              _N|            _N|           _N|              _N|             4|          _N|         1|             _N|CCN6_CDRCCN_4004_...|         _N|  _N|          _N|CDRCCN_4004| 20220501124122|            _N|  TUNTT|          _N|         _N|        TUNISIA|20220501000000|       11|        23|   473.95|    474.0|         _N_0|mobileOriginating|        HOME|         _N|      1031|             _N|      OPTICA|          _N|    500__N|      20220501000000|        12|            HYB|          0|      _UN|TUNISIA-Mobile Tu...|TUNISIA-Mobile Tu...|   _N|           1|3.282094| 3.282094|
|               _N| _N|    _N|21695855811|  21695855811|            _N|          _N|    _N|21694245039|   1A94245039|0_955535523840|    VOICE|               _N|         60055778213|     _N|        _N|              _N|               0.0|  9.06|      9.06|          0|              _N|            _N|           _N|              _N|             3|          _N|         1|             _N|CCN6_CDRCCN_4004_...|         _N|  _N|          _N|CDRCCN_4004| 20220501124123|            _N|  TUNTT|          _N|         _N|        TUNISIA|20220501000000|       11|         5|     9.06|     9.06|         _N_0|mobileOriginating|        HOME|         _N|      1031|             _N|      OPTICA|          _N|    _N_123|      20220501000000|        12|            HYB|          0|      _UN|TUNISIA-Mobile Tu...|TUNISIA-Mobile Tu...|   _N|           1|   0.022|    0.022|
|               _N| _N|    _N|21697417639|  21697417639|            _N|          _N|    _N|21650141676|   1A50141676|0_774739722240|    VOICE|               _N|         60055778214|     _N|        _N|              _N|              0.48|110.64|    111.12|          0|              _N|            _N|           _N|              _N|            40|          _N|         1|             _N|CCN6_CDRCCN_4004_...|         _N|  _N|          _N|CDRCCN_4004| 20220501124046|            _N|  TUNTT|          _N|         _N|        TUNISIA|20220501000000|       11|        31|   110.64|   111.12|         _N_0|mobileOriginating|        HOME|         _N|      1058|             _N|         _UN|          _N|     _N__N|      20220501000000|        12|        PREPAID|          0|      _UN|TUNISIA-Mobile Tu...|TUNISIA-Mobile Or...|   _N|           1|  0.0215|   0.0215|
|               _N| _N|    _N|21697709608|  21697709608|            _N|          _N|    _N|21692280002|   1A92280002|0_551198720000|    VOICE|               _N|         60055778215|     _N|        _N|              _N|             0.035|   0.0|       0.0|          0|              _N|            _N|           _N|              _N|             6|          _N|         1|             _N|CCN6_CDRCCN_4004_...|         _N|  _N|          _N|CDRCCN_4004| 20220501124121|            _N|  TUNTT|          _N|         _N|        TUNISIA|20220501000000|       11|        _N|      0.0|      0.0|         _N_0|mobileOriginating|        HOME|         _N|      1028|             _N|         _UN|          _N|     _N__N|      20220501000000|        12|        PREPAID|          0|      _UN|TUNISIA-Mobile Tu...|TUNISIA-Mobile Tu...|   _N|           1|    0.35|    0.385|
+-----------------+---+------+-----------+-------------+--------------+------------+------+-----------+-------------+--------------+---------+-----------------+--------------------+-------+----------+----------------+------------------+------+----------+-----------+----------------+--------------+-------------+----------------+--------------+------------+----------+---------------+--------------------+-----------+----+------------+-----------+---------------+--------------+-------+------------+-----------+---------------+--------------+---------+----------+---------+---------+-------------+-----------------+------------+-----------+----------+---------------+------------+------------+----------+--------------------+----------+---------------+-----------+---------+--------------------+--------------------+-----+------------+--------+---------+
only showing top 5 rows

MMG
+-----------------+---+------+-----------+--------------------+--------------+------------+------+--------+-------------+--------------+---------+-----------------+--------------------+-------+----------+----------------+------------------+-----+----------+-----------+----------------+--------------+-------------+----------------+--------------+------------+----------+--------------------+--------------------+-----------+----+------------+---+---------------+--------------+-------+------------+-----------+---------------+--------------+---------+----------+---------+---------+-------------+-----------+------------+-----------+----------+---------------+------------+------------+----------+--------------------+----------+---------------+-----------+---------+-----+-----+-----+------------+--------+---------+
|AGGREGATION_GROUP|APN|A_IMSI|   A_MSISDN|       A_MSISDN_ORIG|BEARER_SERVICE|B_DATASOURCE|B_IMSI|B_MSISDN|B_MSISDN_ORIG|CALL_REFERENCE|CALL_TYPE|CAUSE_FOR_CLOSING|CDR_SEARCH_DETAIL_ID|CELL_ID|CGI_ID_KEY|CHARGE_AMNT_STEP|CHARGE_AMOUNT_ORIG|C_NUM|C_NUM_ORIG|DATA_VOLUME|DATA_VOLUME_DOWN|DATA_VOLUME_UP|DURATION_STEP|ESTIMATED_AMOUNT|EVENT_DURATION|EVENT_STATUS|EVENT_TYPE|     EVENT_TYPE_ORIG|            FILENAME|FILTER_CODE|IMEI|LAST_PARTIAL| NE|ORIG_START_TIME|PARTIAL_SEQ_ID|PARTNER|PARTNER_CODE|PGW_ADDRESS|PRICE_PLAN_CODE|     PROC_DATE|PROC_HOUR|RADIO_TYPE|RATE_CODE|RECORD_ID|RECORD_STATUS|RECORD_TYPE|ROAMING_TYPE|SERVED_MSRN|SERVICE_ID|SERVICE_PARTNER|SERVICE_TYPE|SGSN_ADDRESS|SMS_CENTRE|START_DATE_TIME_HOME|START_TIME|SUBSCRIBER_TYPE|TELESERVICE|TEST_FLAG|TON_A|TON_B|TON_C|TRAFFIC_TYPE|TRUNK_IN|TRUNK_OUT|
+-----------------+---+------+-----------+--------------------+--------------+------------+------+--------+-------------+--------------+---------+-----------------+--------------------+-------+----------+----------------+------------------+-----+----------+-----------+----------------+--------------+-------------+----------------+--------------+------------+----------+--------------------+--------------------+-----------+----+------------+---+---------------+--------------+-------+------------+-----------+---------------+--------------+---------+----------+---------+---------+-------------+-----------+------------+-----------+----------+---------------+------------+------------+----------+--------------------+----------+---------------+-----------+---------+-----+-----+-----+------------+--------+---------+
|               _N| _N|    _N|21693418211|23136393334313832...|            _N|          _N|    _N| 2168000|     83030303|            _N|      VAS|               _N|         60059532461|     _N|        _N|              _N|                _N|   _N|        _N|         _N|              _N|            _N|           _N|              _N|            _N|     Success|        74|SMS_mSOriginating...|sicap_internetplu...|        _UN|  _N|          _N|MMG| 20220501080232|            _N|     _N|          _N|         _N|             _N|20220501000000|       08|        _N|       _N|       _N|           _N|        PSM|          _N|         _N|        _N|             _N|          _N|          _N|        _N|                  _N|        _N|        PREPAID|         _N|      _UN|   _N|   _N|   _N|           1|      _N|       _N|
|               _N| _N|    _N|21621886660|23136323138383636...|            _N|          _N|    _N| 2168000|     83030303|            _N|      VAS|               _N|         60059532462|     _N|        _N|              _N|                _N|   _N|        _N|         _N|              _N|            _N|           _N|              _N|            _N|     Success|        74|SMS_mSOriginating...|sicap_internetplu...|        _UN|  _N|          _N|MMG| 20220501080233|            _N|     _N|          _N|         _N|             _N|20220501000000|       08|        _N|       _N|       _N|           _N|        PSM|          _N|         _N|        _N|             _N|          _N|          _N|        _N|                  _N|        _N|        PREPAID|         _N|        1|   _N|   _N|   _N|           1|      _N|       _N|

#Transformation de type des colonnes

In [ ]:
from pyspark.sql.types import IntegerType,BooleanType,DateType,DecimalType,DoubleType
# Convert String to Integer Type

MSCdf.withColumn("EVENT_DURATION",MSCdf.EVENT_DURATION.cast(IntegerType()))

CCNdf.withColumn("EVENT_DURATION",CCNdf.EVENT_DURATION.cast(DoubleType()))
CCNdf.withColumn("DATA_VOLUME",CCNdf.DATA_VOLUME.cast(DoubleType()))
CCNdf.withColumn("CHARGE_AMOUNT_ORIG",CCNdf.CHARGE_AMOUNT_ORIG.cast(DoubleType()))


MMGdf.withColumn("EVENT_DURATION",MMGdf.EVENT_DURATION.cast(IntegerType()))
MMSdf.withColumn("EVENT_DURATION",MMSdf.EVENT_DURATION.cast(IntegerType()))

PSMdf.withColumn("EVENT_DURATION",PSMdf.EVENT_DURATION.cast(IntegerType()))


MMSdf.withColumn("DATA_VOLUME",MMSdf.DATA_VOLUME.cast(DoubleType()))

DataFrame[AGGREGATION_GROUP: string, APN: string, A_IMSI: string, A_MSISDN: string, A_MSISDN_ORIG: string, BEARER_SERVICE: string, B_DATASOURCE: string, B_IMSI: string, B_MSISDN: string, B_MSISDN_ORIG: string, CALL_REFERENCE: string, CALL_TYPE: string, CAUSE_FOR_CLOSING: string, CDR_SEARCH_DETAIL_ID: string, CELL_ID: string, CGI_ID_KEY: string, CHARGE_AMNT_STEP: string, CHARGE_AMOUNT_ORIG: string, C_NUM: string, C_NUM_ORIG: string, DATA_VOLUME: double, DATA_VOLUME_DOWN: string, DATA_VOLUME_UP: string, DURATION_STEP: string, ESTIMATED_AMOUNT: string, EVENT_DURATION: string, EVENT_STATUS: string, EVENT_TYPE: string, EVENT_TYPE_ORIG: string, FILENAME: string, FILTER_CODE: string, IMEI: string, LAST_PARTIAL: string, NE: string, ORIG_START_TIME: string, PARTIAL_SEQ_ID: string, PARTNER: string, PARTNER_CODE: string, PGW_ADDRESS: string, PRICE_PLAN_CODE: string, PROC_DATE: string, PROC_HOUR: string, RADIO_TYPE: string, RATE_CODE: string, RECORD_ID: string, RECORD_STATUS: string, RECORD_TYPE: string, ROAMING_TYPE: string, SERVED_MSRN: string, SERVICE_ID: string, SERVICE_PARTNER: string, SERVICE_TYPE: string, SGSN_ADDRESS: string, SMS_CENTRE: string, START_DATE_TIME_HOME: string, START_TIME: string, SUBSCRIBER_TYPE: string, TELESERVICE: string, TEST_FLAG: string, TON_A: string, TON_B: string, TON_C: string, TRAFFIC_TYPE: string, TRUNK_IN: string, TRUNK_OUT: string]

# Aggregation (Group By, Count, Sum)

In [ ]:
MMG_AGG=MMGdf.groupBy("PROC_DATE","PROC_HOUR","EVENT_TYPE","CALL_TYPE","EVENT_STATUS","SUBSCRIBER_TYPE").agg(
    _count("*").alias("CDR_COUNT"),_count("*").alias("MMG_EVENT_COUNT")).collect()

In [ ]:
MSC_AGG=MSCdf.groupBy("PROC_DATE","PROC_HOUR","EVENT_TYPE","SUBSCRIBER_TYPE","TRAFFIC_TYPE").agg(
    psf.count("*").alias("CDR_COUNT"),psf.sum("EVENT_DURATION").alias("EVENT_DURATION")).collect()

CCN_AGG=CCNdf.groupBy("PROC_DATE","PROC_HOUR","EVENT_TYPE","CALL_TYPE","SUBSCRIBER_TYPE","PARTNER","ROAMING_TYPE","TRAFFIC_TYPE").agg(
    _count("*").alias("CDR_COUNT"),_count("*").alias("CCN_EVENT_COUNT"),_sum("CHARGE_AMOUNT_ORIG").alias("CHARGE_AMOUNT"),psf.sum("DATA_VOLUME").alias("DATA_VOLUME")).collect()

CCN_AGG_msc=CCNdf_msc.groupBy("PROC_DATE","PROC_HOUR","EVENT_TYPE","CALL_TYPE","SUBSCRIBER_TYPE","PARTNER","ROAMING_TYPE","TRAFFIC_TYPE").agg(
    _count("*").alias("CDR_COUNT"),_count("*").alias("CCN_EVENT_COUNT"),_sum("CHARGE_AMOUNT_ORIG").alias("CHARGE_AMOUNT"),psf.sum("DATA_VOLUME").alias("DATA_VOLUME")).collect()

MMS_AGG=MMSdf.groupBy("PROC_DATE","PROC_HOUR","EVENT_TYPE","CALL_TYPE","EVENT_STATUS","TRAFFIC_TYPE","SUBSCRIBER_TYPE","PARTNER").agg(
    _count("*").alias("CDR_COUNT"),psf.sum("DATA_VOLUME").alias("DATA_VOLUME")).collect()

PSM_AGG=PSMdf.groupBy("PROC_DATE","PROC_HOUR","EVENT_TYPE","CALL_TYPE","EVENT_STATUS","SUBSCRIBER_TYPE").agg(
    _count("*").alias("CDR_COUNT"),_count("*").alias("MMG_EVENT_COUNT")).collect()

MMGdf.groupBy("PROC_DATE","PROC_HOUR","EVENT_TYPE","CALL_TYPE","EVENT_STATUS","SUBSCRIBER_TYPE").agg(
    _count("*").alias("CDR_COUNT"),_count("*").alias("MMG_EVENT_COUNT")).collect()

[Row(PROC_DATE='20220501000000', PROC_HOUR='13', EVENT_TYPE='74', CALL_TYPE='VAS', EVENT_STATUS='Success', SUBSCRIBER_TYPE='PREPAID', CDR_COUNT=436, MMG_EVENT_COUNT=436),
 Row(PROC_DATE='20220501000000', PROC_HOUR='08', EVENT_TYPE='75', CALL_TYPE='VAS', EVENT_STATUS='Success', SUBSCRIBER_TYPE='POSTPAID', CDR_COUNT=19, MMG_EVENT_COUNT=19),
 Row(PROC_DATE='20220501000000', PROC_HOUR='11', EVENT_TYPE='74', CALL_TYPE='VAS', EVENT_STATUS='Success', SUBSCRIBER_TYPE='POSTPAID', CDR_COUNT=7, MMG_EVENT_COUNT=7),
 Row(PROC_DATE='20220501000000', PROC_HOUR='16', EVENT_TYPE='75', CALL_TYPE='VAS', EVENT_STATUS='Success', SUBSCRIBER_TYPE='PREPAID', CDR_COUNT=3, MMG_EVENT_COUNT=3),
 Row(PROC_DATE='20220501000000', PROC_HOUR='13', EVENT_TYPE='75', CALL_TYPE='VAS', EVENT_STATUS='Success', SUBSCRIBER_TYPE='PREPAID', CDR_COUNT=45, MMG_EVENT_COUNT=45),
 Row(PROC_DATE='20220501000000', PROC_HOUR='09', EVENT_TYPE='74', CALL_TYPE='VAS', EVENT_STATUS='Success', SUBSCRIBER_TYPE='PREPAID', CDR_COUNT=361, MMG_EVENT_COUNT=361),
 Row(PROC_DATE='20220501000000', PROC_HOUR='09', EVENT_TYPE='74', CALL_TYPE='VAS', EVENT_STATUS='Success', SUBSCRIBER_TYPE='HYB', CDR_COUNT=128, MMG_EVENT_COUNT=128),
 Row(PROC_DATE='20220501000000', PROC_HOUR='11', EVENT_TYPE='75', CALL_TYPE='VAS', EVENT_STATUS='Success', SUBSCRIBER_TYPE='HYB', CDR_COUNT=31, MMG_EVENT_COUNT=31),
 Row(PROC_DATE='20220501000000', PROC_HOUR='12', EVENT_TYPE='74', CALL_TYPE='VAS', EVENT_STATUS='Success', SUBSCRIBER_TYPE='PREPAID', CDR_COUNT=132, MMG_EVENT_COUNT=132),
 Row(PROC_DATE='20220501000000', PROC_HOUR='03', EVENT_TYPE='74', CALL_TYPE='VAS', EVENT_STATUS='Success', SUBSCRIBER_TYPE='PREPAID', CDR_COUNT=161, MMG_EVENT_COUNT=161),
 Row(PROC_DATE='20220501000000', PROC_HOUR='08', EVENT_TYPE='74', CALL_TYPE='VAS', EVENT_STATUS='Success', SUBSCRIBER_TYPE='PREPAID', CDR_COUNT=1133, MMG_EVENT_COUNT=1133),
 Row(PROC_DATE='20220501000000', PROC_HOUR='03', EVENT_TYPE='74', CALL_TYPE='VAS', EVENT_STATUS='Success', SUBSCRIBER_TYPE='HYB', CDR_COUNT=111, MMG_EVENT_COUNT=111),
 Row(PROC_DATE='20220501000000', PROC_HOUR='13', EVENT_TYPE='74', CALL_TYPE='VAS', EVENT_STATUS='Success', SUBSCRIBER_TYPE='POSTPAID', CDR_COUNT=33, MMG_EVENT_COUNT=33),
 Row(PROC_DATE='20220501000000', PROC_HOUR='08', EVENT_TYPE='74', CALL_TYPE='VAS', EVENT_STATUS='Success', SUBSCRIBER_TYPE='HYB', CDR_COUNT=206, MMG_EVENT_COUNT=206),
 Row(PROC_DATE='20220501000000', PROC_HOUR='19', EVENT_TYPE='74', CALL_TYPE='VAS', EVENT_STATUS='Success', SUBSCRIBER_TYPE='HYB', CDR_COUNT=126, MMG_EVENT_COUNT=126),
 Row(PROC_DATE='20220501000000', PROC_HOUR='08', EVENT_TYPE='75', CALL_TYPE='VAS', EVENT_STATUS='Success', SUBSCRIBER_TYPE='PREPAID', CDR_COUNT=13, MMG_EVENT_COUNT=13),
 Row(PROC_DATE='20220501000000', PROC_HOUR='10', EVENT_TYPE='74', CALL_TYPE='VAS', EVENT_STATUS='Success', SUBSCRIBER_TYPE='PREPAID', CDR_COUNT=1, MMG_EVENT_COUNT=1),
 Row(PROC_DATE='20220501000000', PROC_HOUR='11', EVENT_TYPE='74', CALL_TYPE='VAS', EVENT_STATUS='Success', SUBSCRIBER_TYPE='HYB', CDR_COUNT=163, MMG_EVENT_COUNT=163),
 Row(PROC_DATE='20220501000000', PROC_HOUR='08', EVENT_TYPE='74', CALL_TYPE='VAS', EVENT_STATUS='Success', SUBSCRIBER_TYPE='POSTPAID', CDR_COUNT=20, MMG_EVENT_COUNT=20),
 Row(PROC_DATE='20220501000000', PROC_HOUR='09', EVENT_TYPE='74', CALL_TYPE='VAS', EVENT_STATUS='Success', SUBSCRIBER_TYPE='POSTPAID', CDR_COUNT=20, MMG_EVENT_COUNT=20),
 Row(PROC_DATE='20220501000000', PROC_HOUR='11', EVENT_TYPE='75', CALL_TYPE='VAS', EVENT_STATUS='Success', SUBSCRIBER_TYPE='PREPAID', CDR_COUNT=25, MMG_EVENT_COUNT=25),
 Row(PROC_DATE='20220501000000', PROC_HOUR='13', EVENT_TYPE='74', CALL_TYPE='VAS', EVENT_STATUS='Success', SUBSCRIBER_TYPE='HYB', CDR_COUNT=334, MMG_EVENT_COUNT=334),
 Row(PROC_DATE='20220501000000', PROC_HOUR='19', EVENT_TYPE='74', CALL_TYPE='VAS', EVENT_STATUS='Success', SUBSCRIBER_TYPE='POSTPAID', CDR_COUNT=14, MMG_EVENT_COUNT=14),
 Row(PROC_DATE='20220501000000', PROC_HOUR='16', EVENT_TYPE='74', CALL_TYPE='VAS', EVENT_STATUS='Success', SUBSCRIBER_TYPE='PREPAID', CDR_COUNT=221, MMG_EVENT_COUNT=221),
 Row(PROC_DATE='20220501000000', PROC_HOUR='12', EVENT_TYPE='74', CALL_TYPE='VAS', EVENT_STATUS='Success', SUBSCRIBER_TYPE='POSTPAID', CDR_COUNT=9, MMG_EVENT_COUNT=9),
 Row(PROC_DATE='20220501000000', PROC_HOUR='11', EVENT_TYPE='74', CALL_TYPE='VAS', EVENT_STATUS='Success', SUBSCRIBER_TYPE='PREPAID', CDR_COUNT=125, MMG_EVENT_COUNT=125),
 Row(PROC_DATE='20220501000000', PROC_HOUR='12', EVENT_TYPE='74', CALL_TYPE='VAS', EVENT_STATUS='Success', SUBSCRIBER_TYPE='HYB', CDR_COUNT=116, MMG_EVENT_COUNT=116),
 Row(PROC_DATE='20220501000000', PROC_HOUR='13', EVENT_TYPE='75', CALL_TYPE='VAS', EVENT_STATUS='Success', SUBSCRIBER_TYPE='HYB', CDR_COUNT=5, MMG_EVENT_COUNT=5),
 Row(PROC_DATE='20220501000000', PROC_HOUR='16', EVENT_TYPE='74', CALL_TYPE='VAS', EVENT_STATUS='Success', SUBSCRIBER_TYPE='HYB', CDR_COUNT=61, MMG_EVENT_COUNT=61),
 Row(PROC_DATE='20220501000000', PROC_HOUR='19', EVENT_TYPE='74', CALL_TYPE='VAS', EVENT_STATUS='Success', SUBSCRIBER_TYPE='PREPAID', CDR_COUNT=66, MMG_EVENT_COUNT=66),
 Row(PROC_DATE='20220501000000', PROC_HOUR='16', EVENT_TYPE='74', CALL_TYPE='VAS', EVENT_STATUS='Success', SUBSCRIBER_TYPE='POSTPAID', CDR_COUNT=9, MMG_EVENT_COUNT=9),
 Row(PROC_DATE='20220501000000', PROC_HOUR='08', EVENT_TYPE='75', CALL_TYPE='VAS', EVENT_STATUS='Success', SUBSCRIBER_TYPE='HYB', CDR_COUNT=103, MMG_EVENT_COUNT=103),
 Row(PROC_DATE='20220501000000', PROC_HOUR='01', EVENT_TYPE='74', CALL_TYPE='VAS', EVENT_STATUS='Success', SUBSCRIBER_TYPE='HYB', CDR_COUNT=6, MMG_EVENT_COUNT=6),
 Row(PROC_DATE='20220501000000', PROC_HOUR='02', EVENT_TYPE='74', CALL_TYPE='VAS', EVENT_STATUS='Success', SUBSCRIBER_TYPE='HYB', CDR_COUNT=2, MMG_EVENT_COUNT=2),
 Row(PROC_DATE='20220501000000', PROC_HOUR='14', EVENT_TYPE='74', CALL_TYPE='VAS', EVENT_STATUS='Success', SUBSCRIBER_TYPE='POSTPAID', CDR_COUNT=8, MMG_EVENT_COUNT=8),
 Row(PROC_DATE='20220501000000', PROC_HOUR='01', EVENT_TYPE='75', CALL_TYPE='VAS', EVENT_STATUS='Success', SUBSCRIBER_TYPE='HYB', CDR_COUNT=1, MMG_EVENT_COUNT=1),
 Row(PROC_DATE='20220501000000', PROC_HOUR='04', EVENT_TYPE='74', CALL_TYPE='VAS', EVENT_STATUS='Success', SUBSCRIBER_TYPE='PREPAID', CDR_COUNT=18, MMG_EVENT_COUNT=18),
 Row(PROC_DATE='20220501000000', PROC_HOUR='02', EVENT_TYPE='74', CALL_TYPE='VAS', EVENT_STATUS='Success', SUBSCRIBER_TYPE='POSTPAID', CDR_COUNT=4, MMG_EVENT_COUNT=4),
 Row(PROC_DATE='20220501000000', PROC_HOUR='22', EVENT_TYPE='74', CALL_TYPE='VAS', EVENT_STATUS='Success', SUBSCRIBER_TYPE='PREPAID', CDR_COUNT=29, MMG_EVENT_COUNT=29),
 Row(PROC_DATE='20220501000000', PROC_HOUR='01', EVENT_TYPE='75', CALL_TYPE='VAS', EVENT_STATUS='Success', SUBSCRIBER_TYPE='PREPAID', CDR_COUNT=9, MMG_EVENT_COUNT=9),
 Row(PROC_DATE='20220501000000', PROC_HOUR='14', EVENT_TYPE='74', CALL_TYPE='VAS', EVENT_STATUS='Success', SUBSCRIBER_TYPE='PREPAID', CDR_COUNT=88, MMG_EVENT_COUNT=88),
 Row(PROC_DATE='20220501000000', PROC_HOUR='14', EVENT_TYPE='74', CALL_TYPE='VAS', EVENT_STATUS='Success', SUBSCRIBER_TYPE='HYB', CDR_COUNT=16, MMG_EVENT_COUNT=16),
 Row(PROC_DATE='20220501000000', PROC_HOUR='02', EVENT_TYPE='74', CALL_TYPE='VAS', EVENT_STATUS='Success', SUBSCRIBER_TYPE='PREPAID', CDR_COUNT=29, MMG_EVENT_COUNT=29),
 Row(PROC_DATE='20220501000000', PROC_HOUR='22', EVENT_TYPE='74', CALL_TYPE='VAS', EVENT_STATUS='Success', SUBSCRIBER_TYPE='HYB', CDR_COUNT=1, MMG_EVENT_COUNT=1),
 Row(PROC_DATE='20220501000000', PROC_HOUR='01', EVENT_TYPE='74', CALL_TYPE='VAS', EVENT_STATUS='Success', SUBSCRIBER_TYPE='PREPAID', CDR_COUNT=43, MMG_EVENT_COUNT=43)]

#Rename Cols

In [ ]:
import pandas as pd

MSC_AGG= pd.DataFrame(MSC_AGG)
CCN_AGG= pd.DataFrame(CCN_AGG)
CCN_AGG_msc= pd.DataFrame(CCN_AGG_msc)
MMG_AGG= pd.DataFrame(MMG_AGG)
MMS_AGG= pd.DataFrame(MMS_AGG)
PSM_AGG= pd.DataFrame(PSM_AGG)


MSC_AGG = MSC_AGG.rename(columns={0: "START_DATE", 1: "START_HOUR", 2: "EVENT_TYPE",3:"SUBSCRIBER_TYPE",4:"TRAFFIC_TYPE",5:"CDR_COUNT",6:"EVENT_DURATION"})
CCN_AGG = CCN_AGG.rename(columns={0: "START_DATE", 1: "START_HOUR", 2: "EVENT_TYPE",3:"CALL_TYPE",4:"SUBSCRIBER_TYPE",5:"PARTNER",6:"ROAMING_TYPE",7:"TRAFFIC_TYPE",8:"CDR_COUNT",9:"EVENT_DURATION",10:"CHARGE_AMOUNT"})
CCN_AGG_msc = CCN_AGG_msc.rename(columns={0: "START_DATE", 1: "START_HOUR", 2: "EVENT_TYPE",3:"CALL_TYPE",4:"SUBSCRIBER_TYPE",5:"PARTNER",6:"ROAMING_TYPE",7:"TRAFFIC_TYPE",8:"CDR_COUNT",9:"EVENT_DURATION",10:"CHARGE_AMOUNT"})
MMG_AGG = MMG_AGG.rename(columns={0: "START_DATE", 1: "START_HOUR", 2: "EVENT_TYPE",3:"CALL_TYPE",4:"EVENT_STATUS",5:"SUBSCRIBER_TYPE",6:"CDR_COUNT",7:"MMG_EVENT_COUNT"})
MMS_AGG = MMS_AGG.rename(columns={0: "START_DATE", 1: "START_HOUR", 2: "EVENT_TYPE",3:"CALL_TYPE",4:"EVENT_STATUS",5:"TRAFFIC_TYPE",6:"SUBSCRIBER_TYPE",7:"PARTNER",8:"CDR_COUNT",9:"DATA_VOLUME"})
PSM_AGG = PSM_AGG.rename(columns={0: "START_DATE", 1: "START_HOUR", 2: "EVENT_TYPE",3:"CALL_TYPE",4:"EVENT_STATUS",5:"SUBSCRIBER_TYPE",6:"CDR_COUNT",7:"MMG_EVENT_COUNT"})

In [ ]:
MSC_AGG['START_DATE'] = MSC_AGG['START_DATE'].str.slice(0, 8)
CCN_AGG['START_DATE'] = CCN_AGG['START_DATE'].str.slice(0, 8)
CCN_AGG_msc['START_DATE'] = CCN_AGG_msc['START_DATE'].str.slice(0, 8)
MMG_AGG['START_DATE'] = MMG_AGG['START_DATE'].str.slice(0, 8)
MMS_AGG['START_DATE'] = MMS_AGG['START_DATE'].str.slice(0, 8)
PSM_AGG['START_DATE'] = PSM_AGG['START_DATE'].str.slice(0, 8)

In [ ]:
CCN_AGG_msc

In [ ]:
MSC_AGG

,START_DATE,START_HOUR,EVENT_TYPE,SUBSCRIBER_TYPE,TRAFFIC_TYPE,CDR_COUNT,EVENT_DURATION
0,20220413,10,2,POSTPAID,1,9503,846842.0
1,20220413,10,1,MVNO,1,6596,412149.0
2,20220413,10,1,PREPAID,1,707990,45492291.0
3,20220413,10,1,RINB,1,219,23265.0
4,20220413,10,16,PREPAID,1,731291,46075088.0
...,...,...,...,...,...,...,...
71,20220413,13,16,PREPAID,1,1,7200.0
72,20220413,13,2,PREPAID,1,1,7410.0
73,20220413,13,22,RINB,1,1,7200.0
74,20220413,13,1,MVNO,1,1,7200.0
75,20220413,12,16,POSTPAID,1,1,7823.0

In [ ]:
CCN_AGG

,START_DATE,START_HOUR,EVENT_TYPE,CALL_TYPE,SUBSCRIBER_TYPE,PARTNER,ROAMING_TYPE,TRAFFIC_TYPE,CDR_COUNT,EVENT_DURATION,CHARGE_AMOUNT,11
0,20220501,20,5,SMS,PREPAID,TUNTT,HOME,1,2904,2904,86.130,0.0
1,20220501,19,75,VAS,PREPAID,TUNTT,HOME,1,39,39,4.700,0.0
2,20220501,11,1,VOICE,PREPAID,QATB1,ROAM,1,1,1,4.590,0.0
3,20220501,20,1,VOICE,HYB,SAUET,ROAM,1,1,1,39.800,0.0
4,20220501,19,20,MMS,PREPAID,TUNTT,HOME,1,2,2,0.270,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
387,20220501,17,1,VOICE,HYB,TUNTT,HOME,1,6,6,56.150,0.0
388,20220501,15,1,VOICE,HYB,TUNTT,HOME,1,34,34,100.293,0.0
389,20220501,16,5,AUDIOSMS,PREPAID,TUNTT,HOME,1,1,1,0.050,0.0
390,20220501,17,5,AUDIOSMS,PREPAID,TUNTT,HOME,1,1,1,0.050,0.0
391,20220501,10,5,AUDIOSMS,PREPAID,TUNTT,HOME,1,1,1,0.050,0.0

In [ ]:
MMG_AGG

,START_DATE,START_HOUR,EVENT_TYPE,CALL_TYPE,EVENT_STATUS,SUBSCRIBER_TYPE,CDR_COUNT,MMG_EVENT_COUNT
0,20220501,13,74,VAS,Success,PREPAID,436,436
1,20220501,08,75,VAS,Success,POSTPAID,19,19
2,20220501,11,74,VAS,Success,POSTPAID,7,7
3,20220501,16,75,VAS,Success,PREPAID,3,3
4,20220501,13,75,VAS,Success,PREPAID,45,45
5,20220501,09,74,VAS,Success,PREPAID,361,361
6,20220501,09,74,VAS,Success,HYB,128,128
7,20220501,11,75,VAS,Success,HYB,31,31
8,20220501,12,74,VAS,Success,PREPAID,132,132
9,20220501,03,74,VAS,Success,PREPAID,161,161
10,20220501,08,74,VAS,Success,PREPAID,1133,1133
11,20220501,03,74,VAS,Success,HYB,111,111
12,20220501,13,74,VAS,Success,POSTPAID,33,33
13,20220501,08,74,VAS,Success,HYB,206,206
14,20220501,19,74,VAS,Success,HYB,126,126
15,20220501,08,75,VAS,Success,PREPAID,13,13
16,20220501,10,74,VAS,Success,PREPAID,1,1
17,20220501,11,74,VAS,Success,HYB,163,163
18,20220501,08,74,VAS,Success,POSTPAID,20,20
19,20220501,09,74,VAS,Success,POSTPAID,20,20
20,20220501,11,75,VAS,Success,PREPAID,25,25
21,20220501,13,74,VAS,Success,HYB,334,334
22,20220501,19,74,VAS,Success,POSTPAID,14,14
23,20220501,16,74,VAS,Success,PREPAID,221,221
24,20220501,12,74,VAS,Success,POSTPAID,9,9
25,20220501,11,74,VAS,Success,PREPAID,125,125
26,20220501,12,74,VAS,Success,HYB,116,116
27,20220501,13,75,VAS,Success,HYB,5,5
28,20220501,16,74,VAS,Success,HYB,61,61
29,20220501,19,74,VAS,Success,PREPAID,66,66
30,20220501,16,74,VAS,Success,POSTPAID,9,9
31,20220501,08,75,VAS,Success,HYB,103,103
32,20220501,01,74,VAS,Success,HYB,6,6
33,20220501,02,74,VAS,Success,HYB,2,2
34,20220501,14,74,VAS,Success,POSTPAID,8,8
35,20220501,01,75,VAS,Success,HYB,1,1
36,20220501,04,74,VAS,Success,PREPAID,18,18
37,20220501,02,74,VAS,Success,POSTPAID,4,4
38,20220501,22,74,VAS,Success,PREPAID,29,29
39,20220501,01,75,VAS,Success,PREPAID,9,9
40,20220501,14,74,VAS,Success,PREPAID,88,88
41,20220501,14,74,VAS,Success,HYB,16,16
42,20220501,02,74,VAS,Success,PREPAID,29,29
43,20220501,22,74,VAS,Success,HYB,1,1
44,20220501,01,74,VAS,Success,PREPAID,43,43

In [ ]:
MMS_AGG

,START_DATE,START_HOUR,EVENT_TYPE,CALL_TYPE,EVENT_STATUS,TRAFFIC_TYPE,SUBSCRIBER_TYPE,PARTNER,CDR_COUNT,DATA_VOLUME
0,20220401,0,21,MMS,1,1,HYB,_UN,2,0.000000
1,20220401,0,21,MMS,12,1,HYB,TUNTT,5,0.000000
2,20220501,0,21,MMS,12,1,HYB,_UN,139,0.000000
3,20220401,0,21,MMS,1,1,PREPAID,_UN,5,0.000000
4,20220501,0,20,MMS,14,1,PREPAID,_UN,6,0.301758
5,20220401,0,21,MMS,1,1,POSTPAID,_UN,1,0.000000
6,20220501,0,20,MMS,1,1,PREPAID,TUNTT,287,25060.903320
7,20220501,0,21,MMS,13,1,PREPAID,TUNTT,112,8468.913086
8,20220501,0,21,MMS,14,1,POSTPAID,TUNTT,3,0.000000
9,20220401,0,21,MMS,1,1,_N,_UN,2,241.594727
10,20220501,0,21,MMS,1,1,HYB,_UN,14,0.000000
11,20220401,0,20,MMS,1,1,PREPAID,TUNTT,14,2127.922852
12,20220401,0,20,MMS,1,1,HYB,_UN,17,1544.607422
13,20220501,0,21,MMS,14,1,HYB,TUNTT,233,1803.327148
14,20220501,0,21,MMS,1,1,HYB,TUNTT,5,5.645508
15,20220501,0,20,MMS,1,1,POSTPAID,_UN,37,1161.261719
16,20220401,0,21,MMS,13,1,HYB,TUNTT,4,394.859375
17,20220501,0,21,MMS,13,1,HYB,TUNTT,23,1727.139648
18,20220401,0,21,MMS,14,1,PREPAID,TUNTT,22,1054.694336
19,20220501,0,21,MMS,12,1,HYB,TUNTT,14,0.000000
20,20220501,0,20,MMS,1,1,PREPAID,_UN,1113,53464.895508
21,20220501,0,21,MMS,12,1,POSTPAID,TUNTT,2,0.000000
22,20220501,0,20,MMS,1,1,POSTPAID,TUNTT,7,1017.139648
23,20220501,0,20,MMS,1,1,HYB,_UN,432,20886.018555
24,20220501,0,21,MMS,1,1,PREPAID,_UN,31,0.000000
25,20220501,0,21,MMS,12,1,POSTPAID,_UN,11,0.000000
26,20220501,0,21,MMS,12,1,PREPAID,TUNTT,78,0.000000
27,20220401,0,20,MMS,14,1,HYB,TUNTT,1,0.345703
28,20220401,0,21,MMS,12,1,PREPAID,TUNTT,3,0.000000
29,20220401,0,21,MMS,12,1,POSTPAID,_UN,1,0.000000
30,20220401,0,21,MMS,12,1,PREPAID,_UN,45,0.000000
31,20220501,0,20,MMS,14,1,PREPAID,TUNTT,416,32600.387695
32,20220501,0,21,MMS,1,1,PREPAID,TUNTT,18,475.879883
33,20220501,0,21,MMS,1,1,POSTPAID,_UN,1,0.000000
34,20220501,0,20,MMS,14,1,POSTPAID,TUNTT,1,0.356445
35,20220501,0,21,MMS,14,1,PREPAID,TUNTT,416,17730.617188
36,20220501,0,20,MMS,1,1,HYB,TUNTT,110,10029.511719
37,20220501,0,21,MMS,14,1,PREPAID,_UN,6,0.000000
38,20220501,0,20,MMS,14,1,HYB,TUNTT,235,3385.915039
39,20220501,0,21,MMS,12,1,PREPAID,_UN,463,0.000000
40,20220401,0,21,MMS,12,1,HYB,_UN,14,0.000000
41,20220401,0,20,MMS,14,1,PREPAID,TUNTT,21,1933.290039
42,20220401,0,20,MMS,1,1,HYB,TUNTT,10,667.541016
43,20220501,0,21,MMS,1,1,_N,_UN,16,565.681641
44,20220401,0,21,MMS,13,1,PREPAID,TUNTT,10,1193.838867
45,20220401,0,20,MMS,1,1,PREPAID,_UN,47,5119.031250
46,20220430,0,20,MMS,1,1,PREPAID,_UN,18,1616.732422
47,20220430,0,20,MMS,1,1,HYB,_UN,3,4.716797
48,20220430,0,21,MMS,1,1,_N,_UN,1,62.470703
49,20220430,0,20,MMS,1,1,PREPAID,TUNTT,3,157.926758
50,20220501,0,21,MMS,13,1,POSTPAID,TUNTT,1,0.385742
51,20220430,0,20,MMS,14,1,PREPAID,TUNTT,4,115.678711
52,20220430,0,21,MMS,14,1,PREPAID,TUNTT,4,111.569336
53,20220430,0,21,MMS,12,1,PREPAID,_UN,1,0.000000
54,20220430,0,21,MMS,1,1,PREPAID,_UN,1,0.000000
55,20220430,0,21,MMS,12,1,HYB,_UN,1,0.000000

In [ ]:
PSM_AGG

,START_DATE,START_HOUR,EVENT_TYPE,CALL_TYPE,EVENT_STATUS,SUBSCRIBER_TYPE,CDR_COUNT,MMG_EVENT_COUNT
0,20220501,01,74,VAS,Success,HYB,13584,13584
1,20220501,00,75,VAS,Success,PREPAID,2,2
2,20220501,01,74,VAS,Success,POSTPAID,2,2
3,20220501,09,75,VAS,Success,POSTPAID,366,366
4,20220501,09,74,VAS,Success,PREPAID,4974,4974
...,...,...,...,...,...,...,...,...
132,20220501,05,74,VAS,Success,PREPAID,4243,4243
133,20220501,06,74,VAS,Success,PREPAID,4092,4092
134,20220501,05,75,VAS,Success,HYB,1,1
135,20220501,07,74,VAS,Success,PREPAID,2880,2880
136,20220501,08,75,VAS,Success,HYB,194,194

# Exportation Fichier AGG

In [ ]:
MSC_AGG.to_csv("/content/drive/MyDrive/AGG/MSC_AGG.csv")
CCN_AGG.to_csv("/content/drive/MyDrive/AGG/CCN_AGG.csv")
#CCN_AGG_msc.to_csv("/content/drive/MyDrive/AGG/CCN_AGG_msc.csv")
MMG_AGG.to_csv("/content/drive/MyDrive/AGG/MMG_AGG.csv")
MMS_AGG.to_csv("/content/drive/MyDrive/AGG/MMS_AGG.csv")
PSM_AGG.to_csv("/content/drive/MyDrive/AGG/PSM_AGG.csv")

#Reconciliation Join

In [ ]:
MSC_AGG =sqlContext.read.csv(header="true", path = "/content/drive/MyDrive/AGG/MSC_AGG.csv")

CCN_AGG =sqlContext.read.csv(header="true", path = "/content/drive/MyDrive/AGG/CCN_AGG.csv")

#CCN_AGG_msc =sqlContext.read.csv(header="true", path = "/content/drive/MyDrive/AGG/CCN_AGG_msc.csv")

MMG_AGG =sqlContext.read.csv(header="true", path = "/content/drive/MyDrive/AGG/MMG_AGG.csv")

MMS_AGG =sqlContext.read.csv(header="true", path = "/content/drive/MyDrive/AGG/MMS_AGG.csv")

PSM_AGG =sqlContext.read.csv(header="true", path = "/content/drive/MyDrive/AGG/PSM_AGG.csv")

## MSC vs CCN

In [ ]:
CCN_AGG.filter(CCN_AGG.START_HOUR == "12" ).show(50)
MSC_AGG.filter(MSC_AGG.START_HOUR == "12" ).show(50)

+---+----------+----------+----------+---------+---------------+-------+------------+------------+---------+--------------+-------------+-----------+
|_c0|START_DATE|START_HOUR|EVENT_TYPE|CALL_TYPE|SUBSCRIBER_TYPE|PARTNER|ROAMING_TYPE|TRAFFIC_TYPE|CDR_COUNT|EVENT_DURATION|CHARGE_AMOUNT|DATA_VOLUME|
+---+----------+----------+----------+---------+---------------+-------+------------+------------+---------+--------------+-------------+-----------+
|122|  20220413|        12|         1|    VOICE|            HYB|  TUNTT|        HOME|           1|        2|             2|        15.32|        0.0|
+---+----------+----------+----------+---------+---------------+-------+------------+------------+---------+--------------+-------------+-----------+

+---+----------+----------+----------+---------------+------------+---------+--------------+
|_c0|START_DATE|START_HOUR|EVENT_TYPE|SUBSCRIBER_TYPE|TRAFFIC_TYPE|CDR_COUNT|EVENT_DURATION|
+---+----------+----------+----------+---------------+------------+---------+--------------+
| 62|  20220413|        12|        22|           RINB|           1|       16|       86155.0|
| 63|  20220413|        12|        16|        PREPAID|           1|       65|      392189.0|
| 64|  20220413|        12|         2|        PREPAID|           1|       89|      528092.0|
| 65|  20220413|        12|         1|            HYB|           1|       41|      236209.0|
| 66|  20220413|        12|         2|            HYB|           1|       28|      166874.0|
| 67|  20220413|        12|         1|        PREPAID|           1|       23|      130168.0|
| 68|  20220413|        12|        16|            HYB|           1|        6|       29715.0|
| 69|  20220413|        12|         2|       POSTPAID|           1|        1|        6857.0|
| 70|  20220413|        12|         2|           MVNO|           1|        1|        7201.0|
| 75|  20220413|        12|        16|       POSTPAID|           1|        1|        7823.0|
+---+----------+----------+----------+---------------+------------+---------+--------------+

In [ ]:
MSC_CCN=CCN_AGG_msc.join(MSC_AGG,
             ((MSC_AGG.START_DATE == CCN_AGG.START_DATE) &
              (MSC_AGG.START_HOUR == CCN_AGG.START_HOUR) &
              (MSC_AGG.EVENT_TYPE == CCN_AGG.EVENT_TYPE) &
              (MSC_AGG.SUBSCRIBER_TYPE == CCN_AGG.SUBSCRIBER_TYPE) &
              (MSC_AGG.TRAFFIC_TYPE == CCN_AGG.TRAFFIC_TYPE)
              ),"fullouter"
              ).select(
                   MSC_AGG.START_DATE,MSC_AGG.START_HOUR,MSC_AGG.EVENT_TYPE,MSC_AGG.SUBSCRIBER_TYPE,MSC_AGG.TRAFFIC_TYPE,
                   MSC_AGG.CDR_COUNT.alias("MSC_OUT_CDR_COUNT"), CCN_AGG.CDR_COUNT.alias("CCN_OUT_CDR_COUNT"),
                   MSC_AGG.EVENT_DURATION.alias("MSC_OUT_EVENT_DURATION"), CCN_AGG.EVENT_DURATION.alias("CCN_OUT_EVENT_DURATION")
              ).filter(
                        (MSC_AGG["EVENT_TYPE"]== ("1" or "3" or "5"))&
                        (MSC_AGG["SUBSCRIBER_TYPE"]== ("PREPAID" or "HYB"))
                ).collect()


CCN_AGG_msc.join(MSC_AGG,
             ((MSC_AGG.START_DATE == CCN_AGG.START_DATE) &
              (MSC_AGG.START_HOUR == CCN_AGG.START_HOUR) &
              (MSC_AGG.EVENT_TYPE == CCN_AGG.EVENT_TYPE) &
              (MSC_AGG.SUBSCRIBER_TYPE == CCN_AGG.SUBSCRIBER_TYPE) &
              (MSC_AGG.TRAFFIC_TYPE == CCN_AGG.TRAFFIC_TYPE)
              ),"fullouter"
              ).select(
                   MSC_AGG.START_DATE,MSC_AGG.START_HOUR,MSC_AGG.EVENT_TYPE,MSC_AGG.SUBSCRIBER_TYPE,MSC_AGG.TRAFFIC_TYPE,
                   MSC_AGG.CDR_COUNT.alias("MSC_OUT_CDR_COUNT"), CCN_AGG.CDR_COUNT.alias("CCN_OUT_CDR_COUNT"),
                   MSC_AGG.EVENT_DURATION.alias("MSC_OUT_EVENT_DURATION"), CCN_AGG.EVENT_DURATION.alias("CCN_OUT_EVENT_DURATION")
              ).filter(
                        (MSC_AGG["EVENT_TYPE"]== ("1" or "3" or "5"))&
                        (MSC_AGG["SUBSCRIBER_TYPE"]== ("PREPAID" or "HYB"))
                ).show()

+----------+----------+----------+---------------+------------+-----------------+-----------------+----------------------+----------------------+
|START_DATE|START_HOUR|EVENT_TYPE|SUBSCRIBER_TYPE|TRAFFIC_TYPE|MSC_OUT_CDR_COUNT|CCN_OUT_CDR_COUNT|MSC_OUT_EVENT_DURATION|CCN_OUT_EVENT_DURATION|
+----------+----------+----------+---------------+------------+-----------------+-----------------+----------------------+----------------------+
|  20220413|        10|         1|        PREPAID|           1|           707990|            14480|            45492291.0|                 14480|
|  20220413|        11|         1|        PREPAID|           1|            31496|               21|             7301202.0|                    21|
|  20220413|        12|         1|        PREPAID|           1|               23|             null|              130168.0|                  null|
+----------+----------+----------+---------------+------------+-----------------+-----------------+----------------------+----------------------+

## MMG vs CCN

In [ ]:
MMG_CCN=CCN_AGG.join(MMG_AGG,
             ((MMG_AGG.START_DATE == CCN_AGG.START_DATE) &
              (MMG_AGG.START_HOUR == CCN_AGG.START_HOUR) &
              (MMG_AGG.EVENT_TYPE == CCN_AGG.EVENT_TYPE) &
              (MMG_AGG.SUBSCRIBER_TYPE == CCN_AGG.SUBSCRIBER_TYPE)
              ),"fullouter"
              ).select(
                   MMG_AGG.START_DATE,MMG_AGG.START_HOUR,MMG_AGG.EVENT_TYPE,MMG_AGG.SUBSCRIBER_TYPE,
                   MMG_AGG.CDR_COUNT.alias("MMG_OUT_CDR_COUNT"), CCN_AGG.CDR_COUNT.alias("CCN_OUT_CDR_COUNT"),
                   MMG_AGG.MMG_EVENT_COUNT.alias("MMG_OUT_EVENT_COUNT"), CCN_AGG.CCN_EVENT_COUNT.alias("CCN_OUT_EVENT_COUNT")
              ).filter(
                        (MMG_AGG["EVENT_TYPE"]== ("75" or "74"))&
                        (MMG_AGG["SUBSCRIBER_TYPE"]== ("PREPAID" or "HYB"))
                ).collect()


CCN_AGG.join(MMG_AGG,
             ((MMG_AGG.START_DATE == CCN_AGG.START_DATE) &
              (MMG_AGG.START_HOUR == CCN_AGG.START_HOUR) &
              (MMG_AGG.EVENT_TYPE == CCN_AGG.EVENT_TYPE) &
              (MMG_AGG.SUBSCRIBER_TYPE == CCN_AGG.SUBSCRIBER_TYPE)
              ),"fullouter"
              ).select(
                   MMG_AGG.START_DATE,MMG_AGG.START_HOUR,MMG_AGG.EVENT_TYPE,MMG_AGG.SUBSCRIBER_TYPE,
                   MMG_AGG.CDR_COUNT.alias("MMG_OUT_CDR_COUNT"), CCN_AGG.CDR_COUNT.alias("CCN_OUT_CDR_COUNT"),
                   MMG_AGG.MMG_EVENT_COUNT.alias("MMG_OUT_EVENT_COUNT"), CCN_AGG.CCN_EVENT_COUNT.alias("CCN_OUT_EVENT_COUNT")
              ).filter(
                        (MMG_AGG["EVENT_TYPE"]== ("75" or "74"))&
                        (MMG_AGG["SUBSCRIBER_TYPE"]== ("PREPAID" or "HYB"))
                ).show()

AttributeError: ignored

##MMS VS CCN

In [ ]:
MMS_CCN=CCN_AGG.join(MMS_AGG,
             ((MMS_AGG.START_DATE == CCN_AGG.START_DATE) &
              (MMS_AGG.START_HOUR == CCN_AGG.START_HOUR) &
              (MMS_AGG.EVENT_TYPE == CCN_AGG.EVENT_TYPE) 
                            ),"fullouter"
              ).select(
                   MMS_AGG.START_DATE,MMS_AGG.START_HOUR,MMS_AGG.EVENT_TYPE,MMS_AGG.CALL_TYPE,MMS_AGG.TRAFFIC_TYPE,
                   MMS_AGG.CDR_COUNT.alias("MMSC_OUT_CDR_COUNT"), CCN_AGG.CDR_COUNT.alias("CCN_OUT_CDR_COUNT"),
                   MMS_AGG.DATA_VOLUME.alias("MMSC_OUT_DATA_VOLUME")
              ).filter(
                  (MMS_AGG["EVENT_TYPE"]== ("20"))&
                  (MMS_AGG["EVENT_STATUS"]== ("1"))&
                  (MMS_AGG["SUBSCRIBER_TYPE"]== ("PREPAID" or "HYB"))
                  
              ).collect()

CCN_AGG.join(MMS_AGG,
             ((MMS_AGG.START_DATE == CCN_AGG.START_DATE) &
              (MMS_AGG.START_HOUR == CCN_AGG.START_HOUR) &
              (MMS_AGG.EVENT_TYPE == CCN_AGG.EVENT_TYPE) 
                            ),"fullouter"
              ).select(
                   MMS_AGG.START_DATE,MMS_AGG.START_HOUR,MMS_AGG.EVENT_TYPE,MMS_AGG.CALL_TYPE,
                   MMS_AGG.CDR_COUNT.alias("MMSC_OUT_CDR_COUNT"), CCN_AGG.CDR_COUNT.alias("CCN_OUT_CDR_COUNT"),
                   MMS_AGG.DATA_VOLUME.alias("MMSC_OUT_DATA_VOLUME")
              ).filter(
                  (MMS_AGG["EVENT_TYPE"]== ("20"))&
                  (MMS_AGG["EVENT_STATUS"]== ("1"))&
                  (MMS_AGG["PARTNER"]== ("TUNTT"))&
                  (MMS_AGG["SUBSCRIBER_TYPE"]== ("PREPAID" or "HYB"))
                  
              ).show()

+----------+----------+----------+---------+------------------+-----------------+--------------------+
|START_DATE|START_HOUR|EVENT_TYPE|CALL_TYPE|MMSC_OUT_CDR_COUNT|CCN_OUT_CDR_COUNT|MMSC_OUT_DATA_VOLUME|
+----------+----------+----------+---------+------------------+-----------------+--------------------+
|  20220501|         0|        20|      MMS|               287|             null|    25060.9033203125|
|  20220401|         0|        20|      MMS|                14|             null|     2127.9228515625|
|  20220430|         0|        20|      MMS|                 3|             null|      157.9267578125|
+----------+----------+----------+---------+------------------+-----------------+--------------------+

In [ ]:
MMS_CCN.show(1)

NameError: ignored

In [ ]:
#MMS_AGG.show()

**PSM vs CCN**

In [ ]:
PSM_CCN=CCN_AGG.join(PSM_AGG,
             ((PSM_AGG.START_DATE == CCN_AGG.START_DATE) &
              (PSM_AGG.START_HOUR == CCN_AGG.START_HOUR) &
              (PSM_AGG.EVENT_TYPE == CCN_AGG.EVENT_TYPE) &
              (PSM_AGG.SUBSCRIBER_TYPE == CCN_AGG.SUBSCRIBER_TYPE)
              ),"fullouter"
              ).select(
                   PSM_AGG.START_DATE,PSM_AGG.START_HOUR,PSM_AGG.EVENT_TYPE,PSM_AGG.SUBSCRIBER_TYPE,
                   PSM_AGG.CDR_COUNT.alias("MMG_OUT_CDR_COUNT"), CCN_AGG.CDR_COUNT.alias("CCN_OUT_CDR_COUNT")
              ).filter(
                        (PSM_AGG["EVENT_TYPE"]== ("74"))&
                        (PSM_AGG["SUBSCRIBER_TYPE"]== ("PREPAID" or "HYB"))
                ).collect()


CCN_AGG.join(PSM_AGG,
             ((PSM_AGG.START_DATE == CCN_AGG.START_DATE) &
              (PSM_AGG.START_HOUR == CCN_AGG.START_HOUR) &
              (PSM_AGG.EVENT_TYPE == CCN_AGG.EVENT_TYPE) &
              (PSM_AGG.SUBSCRIBER_TYPE == CCN_AGG.SUBSCRIBER_TYPE)
              ),"fullouter"
              ).select(
                   PSM_AGG.START_DATE,PSM_AGG.START_HOUR,PSM_AGG.EVENT_TYPE,PSM_AGG.SUBSCRIBER_TYPE,
                   PSM_AGG.CDR_COUNT.alias("MMG_OUT_CDR_COUNT"), CCN_AGG.CDR_COUNT.alias("CCN_OUT_CDR_COUNT")
              ).filter(
                        (PSM_AGG["EVENT_TYPE"]== ("74"))&
                        (PSM_AGG["SUBSCRIBER_TYPE"]== ("PREPAID" or "HYB"))
                ).show()

+----------+----------+----------+---------------+-----------------+-----------------+
|START_DATE|START_HOUR|EVENT_TYPE|SUBSCRIBER_TYPE|MMG_OUT_CDR_COUNT|CCN_OUT_CDR_COUNT|
+----------+----------+----------+---------------+-----------------+-----------------+
|  20220501|        09|        74|        PREPAID|             4974|              186|
|  20220501|        08|        74|        PREPAID|             6528|              342|
|  20220501|        00|        74|        PREPAID|              382|             6691|
|  20220501|        01|        74|        PREPAID|           135662|             1366|
|  20220501|        13|        74|        PREPAID|             9773|              601|
|  20220501|        23|        74|        PREPAID|            22684|             null|
|  20220501|        12|        74|        PREPAID|             9971|             1146|
|  20220501|        22|        74|        PREPAID|            15621|              585|
|  20220501|        10|        74|        PREPAID|             5957|              821|
|  20220501|        20|        74|        PREPAID|            11055|             1002|
|  20220501|        14|        74|        PREPAID|            17801|              538|
|  20220501|        21|        74|        PREPAID|            19073|             1722|
|  20220501|        15|        74|        PREPAID|            16509|             null|
|  20220501|        02|        74|        PREPAID|            28317|             1117|
|  20220501|        03|        74|        PREPAID|            14864|              747|
|  20220501|        04|        74|        PREPAID|             8526|              428|
|  20220501|        18|        74|        PREPAID|             8874|               58|
|  20220501|        16|        74|        PREPAID|            12872|             null|
|  20220501|        11|        74|        PREPAID|             4671|              800|
|  20220501|        17|        74|        PREPAID|            10549|             null|
+----------+----------+----------+---------------+-----------------+-----------------+
only showing top 20 rows

# Exportation Fichier Val

In [ ]:
import pandas as pd

MSC_CCN= pd.DataFrame(MSC_CCN)

MSC_CCN = MSC_CCN.rename(columns={0: "START_DATE", 1: "START_HOUR", 2: "EVENT_TYPE",3:"SUBSCRIBER_TYPE",4:"TRAFFIC_TYPE",5:"MSC_OUT_CDR_COUNT",6:"CCN_OUT_CDR_COUNT",7:"MSC_OUT_EVENT_DURATION",8:"CCN_OUT_EVENT_DURATION"})

In [ ]:
MMG_CCN

[Row(START_DATE='20220501', START_HOUR='16', EVENT_TYPE='75', SUBSCRIBER_TYPE='PREPAID', MMG_OUT_CDR_COUNT='3', CCN_OUT_CDR_COUNT=None, MMG_OUT_EVENT_COUNT='3', CCN_OUT_EVENT_COUNT=None),
 Row(START_DATE='20220501', START_HOUR='13', EVENT_TYPE='75', SUBSCRIBER_TYPE='PREPAID', MMG_OUT_CDR_COUNT='45', CCN_OUT_CDR_COUNT='68', MMG_OUT_EVENT_COUNT='45', CCN_OUT_EVENT_COUNT='68'),
 Row(START_DATE='20220501', START_HOUR='08', EVENT_TYPE='75', SUBSCRIBER_TYPE='PREPAID', MMG_OUT_CDR_COUNT='13', CCN_OUT_CDR_COUNT='886', MMG_OUT_EVENT_COUNT='13', CCN_OUT_EVENT_COUNT='886'),
 Row(START_DATE='20220501', START_HOUR='11', EVENT_TYPE='75', SUBSCRIBER_TYPE='PREPAID', MMG_OUT_CDR_COUNT='25', CCN_OUT_CDR_COUNT='307', MMG_OUT_EVENT_COUNT='25', CCN_OUT_EVENT_COUNT='307'),
 Row(START_DATE='20220501', START_HOUR='01', EVENT_TYPE='75', SUBSCRIBER_TYPE='PREPAID', MMG_OUT_CDR_COUNT='9', CCN_OUT_CDR_COUNT=None, MMG_OUT_EVENT_COUNT='9', CCN_OUT_EVENT_COUNT=None)]

In [ ]:
MMG_CCN.to_csv("/content/drive/MyDrive/AGG/MMG_CCN.csv")

AttributeError: ignored

In [ ]:
import pandas as pd

a=pd.read_csv('/content/drive/MyDrive/Réconcilliation/MSC_CCN_VOIX_SMS.csv',error_bad_lines=False,sep=";")

In [ ]:
a